### ISSUE TITLE
界面部分内容对齐建议

### ISSUE THREAD

**Issue by Tjohn98** [Hami-Lemon/Wabby_Wabbo_UI#1]
![感觉没对齐有点不好看](https://user-images.githubusercontent.com/61076246/139480040-94dab220-c3d0-4fcf-8f12-c6cd579299eb.png)
>

**Comment by Hami-Lemon** [comment]
你好，非常感谢对这个项目提出issue，这个项目是我和舍友的一个大作业，目前我们都有各种学习上的琐事，所以目前处于随缘维护的状态，非常抱歉。

**Comment by kafuumi** [comment]
你好，非常感谢对这个项目提出issue，对于这个对齐问题，其实我们最初的设计就是这样，上面的热评栏显示获赞数最高的三个评论，这三个评论框一起居中显示，并没有考虑与下面的框对齐，但我们会考虑你的建议，谢谢！

**Comment by Tjohn98** [comment]
OK
